services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: rust-backend
    environment:
      - LOG_LEVEL=debug
      - DB_HOST=todooo_db
      - DB_PORT=3306
      - DB_NAME=todooo_db
      - DB_USER_FILE=/run/secrets/todooo_db_user
      - DB_PASS_FILE=/run/secrets/todooo_db_password
      - CACHE_HOST=cache
    secrets:
      - todooo_db_user
      - todooo_db_password

  todooo_db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: todooo_db
      MYSQL_USER_FILE: /run/secrets/todooo_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/todooo_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/todooo_db_root_password
    secrets:
      - todooo_db_user
      - todooo_db_password
      - todooo_db_root_password
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
  cache:
    image: redis:7.0
    ports:
      - "6379:6379"
    container_name: redis-cache

volumes:
  db_data:

secrets:
  todooo_db_password:
    file: ./secrets/todooo_db_password.txt
  todooo_db_root_password:
    file: ./secrets/todooo_db_root_password.txt
  todooo_db_user:
    file: ./secrets/todooo_db_user.txt