services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: rust-backend
    environment:
      - LOG_LEVEL=debug
      - DB_HOST=tedooo_db
      - DB_PORT=3306
      - DB_NAME=tedooo_db
      - DB_USER_FILE=/run/secrets/tedooo_db_user
      - DB_PASS_FILE=/run/secrets/tedooo_db_password
      - CACHE_HOST=cache
      - CACHE_PORT=6379
    secrets:
      - tedooo_db_user
      - tedooo_db_password

  tedooo_db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: tedooo_db
      MYSQL_USER_FILE: /run/secrets/tedooo_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/tedooo_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/tedooo_db_root_password
    secrets:
      - tedooo_db_user
      - tedooo_db_password
      - tedooo_db_root_password
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
  cache:
    image: redis:7.0
    ports:
      - "6379:6379"
    container_name: redis-cache

volumes:
  db_data:

secrets:
  tedooo_db_password:
    file: ./secrets/tedooo_db_password.txt
  tedooo_db_root_password:
    file: ./secrets/tedooo_db_root_password.txt
  tedooo_db_user:
    file: ./secrets/tedooo_db_user.txt